baseurl      = "https://northern-call-path.github.io/"
languageCode = "en-us"
title        = "Northern Call"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

hasCJKLanguage = false
disqusShortname = "hugo-theme-stack"

[pagination]
    pagerSize = 5
